create table public.announcements (
  id integer generated by default as identity not null,
  title text null,
  link text null,
  datetime timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  announcement_id integer null,
  constraint cbx_comunicados_pkey primary key (id),
  constraint cbx_comunicados_cbx_id_key unique (announcement_id),
  constraint cbx_comunicados_cbx_link_key unique (link)
) TABLESPACE pg_default;


create table public.news (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  news_id integer null,
  title text null,
  link text null,
  datetime timestamp with time zone null,
  constraint news_pkey primary key (id),
  constraint news_news_id_key unique (news_id)
) TABLESPACE pg_default;


create table public.players (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  cbx_id text null,
  name text null,
  birth_date text null,
  state text null,
  fide_id text null,
  classical text null,
  rapid text null,
  blitz text null,
  constraint players_pkey primary key (id),
  constraint players_cbx_id_key unique (cbx_id)
) TABLESPACE pg_default;


create table public.tournaments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  cbx_id text null,
  organizer text null,
  location text null,
  period text null,
  notes text null,
  regulation_url text null,
  status text null,
  rhythm text null,
  rating text null,
  players_count text null,
  fide_players_count text null,
  constraint tournaments_pkey primary key (id),
  constraint tournaments_cbx_id_key unique (cbx_id)
) TABLESPACE pg_default;